default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "clinicast") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "clinicast") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "reminders_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "reminders_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "reminders_production") %>
