# Generated by Django 4.2.28 on 2026-02-22 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_id', models.IntegerField()),
                ('scheduled_datetime', models.DateTimeField()),
                ('appointment_type', models.CharField(choices=[('GP', 'GP'), ('telehealth', 'Telehealth'), ('walk-in', 'Walk-in')], max_length=20)),
                ('booked_lead_time_days', models.IntegerField()),
                ('reminders_sent', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('showed', 'Showed'), ('no-show', 'No-show'), ('cancelled', 'Cancelled')], max_length=15)),
                ('noshow_probability', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=7)),
                ('registration_date', models.DateField()),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('email', 'Email')], max_length=10)),
                ('sent_at', models.DateTimeField()),
                ('opened', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clinic.appointment')),
            ],
            options={
                'db_table': 'reminders',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.patient'),
        ),
    ]
