source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "pg", "~> 1.5"
# json 3.x changes JSON.parse/generate arity and breaks webmock and faraday
gem "json", "~> 2.7"
gem "puma", ">= 5.0"
gem "bootsnap", require: false

# background work
gem "sidekiq", "~> 7.3"
gem "sidekiq-cron", "~> 2.0"

# talking to the scoring service
gem "faraday", "~> 2.9"
gem "faraday-retry", "~> 2.2"

gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails", "~> 7.1"
  gem "factory_bot_rails", "~> 6.4"
end

group :test do
  gem "webmock", "~> 3.23"
  gem "shoulda-matchers", "~> 6.4"
end
